### ISSUE TITLE
Grafana Admin password

### ISSUE THREAD

**Issue by NiceRath** [O-X-L/dmarc-analyzer#1]
The grafana admin password could be set by default. (if `GF_AUTH_ANONYMOUS_ENABLED: 'true'`)

```yaml
    env_file:
      - '{{ path.config }}/grafana.env'
    command:
      - 'sh'
      - '-c'
      - 'grafana cli admin reset-admin-password ${GF_SECURITY_ADMIN_PASSWORD} && /run.sh'
```
